### ISSUE TITLE
Can not run migrations

### ISSUE THREAD

**Issue by laynemcnish** [gobuffalo/buffalo-heroku#14]
Hello!

I was trying to follow along with your [blog post and video](https://blog.gobuffalo.io/deploying-buffalo-to-heroku-with-docker-adafa4afdd6f) on how to set up Heroku with Buffalo and ran into some issues.  

The main issue is that I can not seem to figure out how to run migrations.

I created this [example app](https://github.com/laynemcnish/example-buffalo-app) to show what I have as far as Dockerfile, migrations, etc and it is on [Heroku](https://lm-myawesomeapp.herokuapp.com), as well.

I was able to deploy successfully by running:
```
$ heroku config:set GO_ENV=production
$ heroku addons:create heroku-postgresql:hobby-dev
$ heroku container:push web
$ heroku open
```

but if I go to `/posts`, it returns an errors in the logs that the table `posts` does not exist.

I then ran:
```
$ heroku run /bin/app migrate
Running /bin/app migrate on ⬢ lm-myawesomeapp... up, run.5234 (Free)
```
which returned no output after that and when I checked for the `posts` table, it still did not exist.

I also tried `buffalo heroku deploy` and `heroku container:release web` and a bunch of other combinations but nothing seemed to get the migrations to run.

Version info:
Buffalo version is: v0.14.9 
go version go1.13.1 darwin/amd64
packr version v2.5.3

Let me know if you need any other information!

**Comment by laynemcnish** [comment]
Possibly related to https://github.com/gobuffalo/buffalo/issues/1795

**Comment by sio4** [comment]
Thank you Layne for the reporting.

I am checking and fixing existing issues on the buffalo family and I found it. It is a quite an old issue with the old version of buffalo and others, so I am not sure if it still exists or is feasible. Please let me know if you need help on this, otherwise, I will close this issue in the next review.

**Comment by laynemcnish** [comment]
Since I couldn't ever get buffalo to work originally, we went with a different solution.  I haven't tried this recently so it's probably better to close this issue and if anyone still has the same problems, they can open a more up to date issue.
