### ISSUE TITLE
Using Go modules and buffalo heroku deploy on Heroku good and fast without Docker.

### ISSUE THREAD

**Issue by frederikhors** [gobuffalo/buffalo-heroku#5]
Using a new default buffalo app and go.mod (Go modules) and this plugin I can use the `buffalo deploy` command and it'll deploy a new app on Heroku without Docker and everything works!

Just I don't know how to call `buffalo pop migrate` now.

**Comment by rafaelcpalmeida** [comment]
@markbates any comments/updates on this?

**Comment by markbates** [comment]
Only that, I don't understand the question or comment this issue is about. Can you clarify?

**Comment by paganotoni** [comment]
I was going to say the same. @rafaelcpalmeida if you can detail a bit more on this issue, I'll be thrilled to try and help.

**Comment by rafaelcpalmeida** [comment]
It seems that @frederikhors is deploying to Heroku without Docker but he's unable to run `buffalo pop migrate`. Is there any way to deploy to Heroku without using Docker?

**Comment by markbates** [comment]
I'm sure there is, but you would have to read Heroku's documentation on how to deploy binaries, and then how to call them. This plugin assumes using Docker.

**Comment by rafaelcpalmeida** [comment]
Using Heroku's way of building binaries and using `bin/app-name migrate` won't execute migrations. According to docs it was supposed to run migrations, right?

**Comment by markbates** [comment]
It's supposed to. The ticket says `buffalo pop migrate` which isn't `bin/app-name migrate`, so my assumption is he's running the wrong command on Heroku. There isn't any log output, or other information to clarify.
